### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by jisungbin** [jisungbin/Covid19CenterApp#13]
- [x] 네트워크 미연결시 예외 처리
- [x] API 요청 중 발생하는 예외 처리
- [x] 앱 이름 설정
- [x] 메모리 누수 없나 검토
- [x] README 작성
- [x] CI 테스트 고치기
